// Generated by CoffeeScript 1.7.1
(function() {
  var bufferSize, context, node, sampleDuration, t, volume,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  context = null;

  node = null;

  sampleDuration = null;

  t = 0;

  volume = 0.1;

  bufferSize = 4096;

  window.potzy = new ((function() {
    function _Class() {
      this.init = __bind(this.init, this);
      this.readyCallbacks = [];
    }

    _Class.prototype.init = function() {
      var cb, e, _i, _len, _ref;
      try {
        if (window.AudioContext == null) {
          window.AudioContext = window.webkitAudioContext;
        }
        context = new AudioContext();
        sampleDuration = 1 / context.sampleRate;
        node = context.createScriptProcessor(bufferSize, 1, 1);
        node.loop = false;
        node.onaudioprocess = (function(_this) {
          return function(e) {
            var i, output, _i, _ref, _results;
            output = e.outputBuffer.getChannelData(0);
            _results = [];
            for (i = _i = 0, _ref = output.length; 0 <= _ref ? _i < _ref : _i > _ref; i = 0 <= _ref ? ++_i : --_i) {
              t += sampleDuration;
              _results.push(output[i] = volume * _this.fn(t));
            }
            return _results;
          };
        })(this);
        this.ready = true;
        _ref = this.readyCallbacks;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          cb = _ref[_i];
          cb();
        }
        return delete this.readyCallbacks;
      } catch (_error) {
        e = _error;
        this.ready = false;
        return alert('Web Audio API is not supported in this browser');
      }
    };

    _Class.prototype.play = function() {
      return node.connect(context.destination);
    };

    _Class.prototype.pause = function() {
      return node.disconnect();
    };

    _Class.prototype.fn = function(t) {
      return Math.sin(2 * Math.PI * t * 440);
    };

    _Class.prototype.onReady = function(fn) {
      if (this.ready) {
        return setTimeout(fn, 0);
      } else {
        return this.readyCallbacks.push(fn);
      }
    };

    return _Class;

  })());

  window.addEventListener('load', window.potzy.init, false);

}).call(this);
